displayName=Teleport Blocker
author=vividflash
description=Teleport Removal Options for most things
tags=teleport,block,chunk,locked,transport,ship,spell,boat,misclick
plugins=com.vividflash.teleportblocker.TeleportBlockerPlugin
build=standard
version=1.4
