displayName=Teleport Blocker
author=vividflash
description=Teleport Option Removal For Standard Spellbook
tags=teleport,block,spellbook,chunk,locked,restriction
plugins=com.vividflash.teleportblocker.TeleportBlockerPlugin
build=standard
version=1.0
