displayName=Teleport Blocker
author=vividflash
description=Teleport Option Removal: Minigames, Spells, Jewellery
tags=teleport,block,spellbook,chunk,locked,restriction,minigame
plugins=com.vividflash.teleportblocker.TeleportBlockerPlugin
build=standard
version=1.1
