/*
 * Copyright (c) 2026, vividflash
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.vividflash.teleportblocker;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.function.Predicate;
import net.runelite.api.gameval.NpcID;

/**
 * The charter ships. Every Trader Stan and Trader Crewmember opens the same
 * chartering menu, which offers each port as a pin on its map and as a line
 * of its list, and a picked port is confirmed in a chat dialogue that names
 * the port and its fare.
 */
public final class CharterShip
{
    /** The crew option that sails straight to the last port chartered to, followed by that port's name. */
    public static final String PREVIOUS_OPTION = "Charter-to";

    /** The line of the confirm dialogue that pays the fare and sails. */
    public static final String CONFIRM_OPTION = "Okay";

    /** The start of the confirm dialogue's title, ahead of the port's name. */
    private static final String CONFIRM_START = "Sailing to ";

    /** The part of the confirm dialogue's title that follows the port's name. */
    private static final String CONFIRM_COST = " costs ";

    /**
     * Trader Stan and the Trader Crewmembers, in every form they take at every
     * port, including the crews of the patrolling charter ships.
     */
    private static final Set<Integer> CREW_IDS = Collections.unmodifiableSet(new HashSet<>(Arrays.asList(
        NpcID.SAILING_TRANSPORT_TRADER_STAN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_BASE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_BRIMHAVEN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CATHERBY,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_MOSLEHARMLESS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_MUSAPOINT,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_PORTKHAZARD,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_PORTPHASMATYS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_PORTSARIM,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_SHIPYARD,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CORSAIRCOVE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_PRIFDDINAS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_PORTTYRAS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_BASE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_BRIMHAVEN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_CATHERBY,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_MOSLEHARMLESS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_MUSAPOINT,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_PORTKHAZARD,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_PORTPHASMATYS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_PORTSARIM,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_SHIPYARD,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_PORTTYRAS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_CORSAIRCOVE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_PRIFDDINAS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_BASE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_BRIMHAVEN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_CATHERBY,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_MOSLEHARMLESS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_MUSAPOINT,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_PORTKHAZARD,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_PORTPHASMATYS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_PORTSARIM,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_SHIPYARD,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_PORTTYRAS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_CORSAIRCOVE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_PRIFDDINAS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_BASE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_BRIMHAVEN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_CATHERBY,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_MOSLEHARMLESS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_MUSAPOINT,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_PORTKHAZARD,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_PORTPHASMATYS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_PORTSARIM,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_SHIPYARD,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_PORTTYRAS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_CORSAIRCOVE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_PRIFDDINAS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_BASE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_BRIMHAVEN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_CATHERBY,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_MOSLEHARMLESS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_MUSAPOINT,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_PORTKHAZARD,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_PORTPHASMATYS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_PORTSARIM,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_SHIPYARD,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_PORTTYRAS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_CORSAIRCOVE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_PRIFDDINAS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_BASE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_BRIMHAVEN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_CATHERBY,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_MOSLEHARMLESS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_MUSAPOINT,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_PORTKHAZARD,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_PORTPHASMATYS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_PORTSARIM,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_SHIPYARD,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_PORTTYRAS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_CORSAIRCOVE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_PRIFDDINAS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_BASE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_BRIMHAVEN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_CATHERBY,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_MOSLEHARMLESS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_MUSAPOINT,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_PORTKHAZARD,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_PORTPHASMATYS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_PORTSARIM,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_SHIPYARD,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_PORTTYRAS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_CORSAIRCOVE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_PRIFDDINAS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_PISCARILIUS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_LANDSEND,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_PISCARILIUS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_LANDSEND,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_PISCARILIUS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_LANDSEND,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_PISCARILIUS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_LANDSEND,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_PISCARILIUS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_LANDSEND,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_PISCARILIUS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_LANDSEND,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_PISCARILIUS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_LANDSEND,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_FORTIS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_ALDARIN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_SUNSETCOAST,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_TEMPESTUS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_FORTIS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_ALDARIN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_SUNSETCOAST,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_TEMPESTUS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_FORTIS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_ALDARIN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_SUNSETCOAST,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_TEMPESTUS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_FORTIS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_ALDARIN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_SUNSETCOAST,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_TEMPESTUS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_FORTIS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_ALDARIN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_SUNSETCOAST,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_TEMPESTUS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_FORTIS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_ALDARIN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_SUNSETCOAST,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_TEMPESTUS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_FORTIS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_ALDARIN,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_SUNSETCOAST,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_TEMPESTUS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_PANDEMONIUM,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_PANDEMONIUM,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_PANDEMONIUM,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_PANDEMONIUM,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_PANDEMONIUM,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_PANDEMONIUM,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_PANDEMONIUM,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_SUMMER_SHORE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_SUMMER_SHORE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_SUMMER_SHORE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_SUMMER_SHORE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_SUMMER_SHORE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_SUMMER_SHORE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_SUMMER_SHORE,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_RED_ROCK,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_RED_ROCK,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_RED_ROCK,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_RED_ROCK,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_RED_ROCK,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_RED_ROCK,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_RED_ROCK,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_BARRACUDA_HQ,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_BARRACUDA_HQ,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_BARRACUDA_HQ,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_BARRACUDA_HQ,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_BARRACUDA_HQ,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_BARRACUDA_HQ,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_BARRACUDA_HQ,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_DEEPFIN_POINT,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_DEEPFIN_POINT,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_DEEPFIN_POINT,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_DEEPFIN_POINT,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_DEEPFIN_POINT,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_DEEPFIN_POINT,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_DEEPFIN_POINT,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_PORT_ROBERTS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN1_PORT_ROBERTS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN2_PORT_ROBERTS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_MAN3_PORT_ROBERTS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN1_PORT_ROBERTS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN2_PORT_ROBERTS,
        NpcID.SAILING_TRANSPORT_TRADER_STAN_CREW_WOMAN3_PORT_ROBERTS)));

    private CharterShip()
    {
    }

    public static boolean isCrew(int npcId)
    {
        return CREW_IDS.contains(npcId);
    }

    /** The port a Charter-to option names, or null when the option is not Charter-to. */
    public static String previousPort(String option)
    {
        if (!option.regionMatches(true, 0, PREVIOUS_OPTION, 0, PREVIOUS_OPTION.length()))
        {
            return null;
        }
        return option.substring(PREVIOUS_OPTION.length()).trim();
    }

    /** The port the confirm dialogue's title names, or null when the text is not that title. */
    public static String confirmPort(String title)
    {
        if (!title.regionMatches(true, 0, CONFIRM_START, 0, CONFIRM_START.length()))
        {
            return null;
        }
        int cost = title.indexOf(CONFIRM_COST);
        return cost > CONFIRM_START.length() ? title.substring(CONFIRM_START.length(), cost).trim() : null;
    }

    /**
     * The ports of the chartering menu in list order, each paired with the
     * name its pin and line carry and the toggle that blocks it. The Karamja
     * Shipyard port is also known as plain Shipyard, so both names are
     * matched. The Charter-to option has a toggle of its own, which removes it
     * whatever port it names.
     */
    public enum Port
    {
        PORT_SARIM(TeleportBlockerConfig::charterPortSarim, "Port Sarim"),
        BRIMHAVEN(TeleportBlockerConfig::charterBrimhaven, "Brimhaven"),
        CATHERBY(TeleportBlockerConfig::charterCatherby, "Catherby"),
        MOS_LE_HARMLESS(TeleportBlockerConfig::charterMosLeHarmless, "Mos Le'Harmless"),
        MUSA_POINT(TeleportBlockerConfig::charterMusaPoint, "Musa Point"),
        PORT_KHAZARD(TeleportBlockerConfig::charterPortKhazard, "Port Khazard"),
        PORT_PHASMATYS(TeleportBlockerConfig::charterPortPhasmatys, "Port Phasmatys"),
        KARAMJA_SHIPYARD(TeleportBlockerConfig::charterKaramjaShipyard, "Karamja Shipyard", "Shipyard"),
        PORT_TYRAS(TeleportBlockerConfig::charterPortTyras, "Port Tyras"),
        CORSAIR_COVE(TeleportBlockerConfig::charterCorsairCove, "Corsair Cove"),
        PRIFDDINAS(TeleportBlockerConfig::charterPrifddinas, "Prifddinas"),
        PORT_PISCARILIUS(TeleportBlockerConfig::charterPortPiscarilius, "Port Piscarilius"),
        LANDS_END(TeleportBlockerConfig::charterLandsEnd, "Land's End"),
        CIVITAS_ILLA_FORTIS(TeleportBlockerConfig::charterCivitasIllaFortis, "Civitas illa Fortis"),
        ALDARIN(TeleportBlockerConfig::charterAldarin, "Aldarin"),
        SUNSET_COAST(TeleportBlockerConfig::charterSunsetCoast, "Sunset Coast"),
        THE_PANDEMONIUM(TeleportBlockerConfig::charterThePandemonium, "The Pandemonium"),
        THE_SUMMER_SHORE(TeleportBlockerConfig::charterTheSummerShore, "The Summer Shore"),
        RED_ROCK(TeleportBlockerConfig::charterRedRock, "Red Rock"),
        DEEPFIN_POINT(TeleportBlockerConfig::charterDeepfinPoint, "Deepfin Point"),
        PORT_ROBERTS(TeleportBlockerConfig::charterPortRoberts, "Port Roberts");

        private final Predicate<TeleportBlockerConfig> blocked;
        private final List<String> portNames;

        Port(Predicate<TeleportBlockerConfig> blocked, String... portNames)
        {
            this.blocked = blocked;
            this.portNames = Collections.unmodifiableList(Arrays.asList(portNames));
        }

        public boolean isBlocked(TeleportBlockerConfig config)
        {
            return blocked.test(config);
        }

        /** True when the text is one of the names this port carries. */
        public boolean matchesName(String text)
        {
            String name = StripAndLowercase.of(text);
            for (String portName : portNames)
            {
                if (!name.isEmpty() && StripAndLowercase.of(portName).equals(name))
                {
                    return true;
                }
            }
            return false;
        }

        @Override
        public String toString()
        {
            return portNames.get(0);
        }
    }
}
